name: Streamlit App CI

on:
  push:
    branches: [ "main", "streamlit-app" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system deps
      run: sudo apt-get update && sudo apt-get install -y ffmpeg

    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Basic import test
      run: |
        python -c "import streamlit, librosa, pandas, matplotlib, plotly, soundfile, numpy, scipy; print('Imports OK')"

    - name: Smoke run Streamlit (headless)
      run: |
        streamlit run carnatic_swara_viz.py --server.headless true --server.port 8501 & sleep 10; pkill -f streamlit || true

    - name: Save artifact (optional)
      uses: actions/upload-artifact@v4
      with:
        name: carnatic-viz
        path: carnatic_swara_viz.py
